# Don't print a new line at the start of the prompt
add_newline = false

# Order of modules on prompt
format = """\
        $time\
        $username\
        $hostname\
        $directory\
        $docker_context\
        $git_branch\
        $git_commit\
        $git_status\
        $git_state\
        $python\
        $swift\
        $package\
        $conda\
        $env_var\
        $line_break\
        $battery\
        $shlvl\
        $jobs\
        $status\
        $character\
    """

[character]
format = "$symbol "
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"
vicmd_symbol = "[â®](bold green)"

[line_break]
disabled = false

[battery]
full_symbol = "ï•¸"
charging_symbol = "ï–‡ "
discharging_symbol = "ï–Œ "
unknown_symbol = "ï–"
empty_symbol = "ï–"
format = "[[î‚´](bg:#DE935F fg:#A6A6A6)$symbol$percentage[î‚´](bg:#A6A6A6 fg:#DE935F)]($style)"
[[battery.display]]
threshold = 10
style = "bold bg:#DE935F fg:#EEEEEE"
[[battery.display]]
threshold = 20
style = "bg:#DE935F fg:#111111"

[conda]
symbol = "ğŸ…’ "
style = "bg:#a4b595 fg:#111111"
ignore_base = true
truncation_length = 1
format = "[[î‚´](bg:#a4b595 fg:#A6A6A6)$symbol$environment[î‚´](bg:#A6A6A6 fg:#a4b595)]($style)"

[directory]
symbol = "ğŸ“ "
style = "bold cyan"
read_only = "ğŸ”’"
read_only_style = "bg:#FF6E79 fg:#EEEEEE"
truncation_length = 0
truncate_to_repo = true

[docker_context]
symbol = "ğŸ³ "
style = "bg:#3A91DC fg:#EEEEEE"
only_with_files = true

[env_var]
disabled = true
symbol = "î• "
style = "bg:#545B68 fg:#EEEEEE"
variable = "0"
default = "fish"
format = "([[î‚´](bg:#545B68 fg:#A6A6A6)$symbol$env_value[î‚´](bg:#A6A6A6 fg:#545B68)]($style))"

[git_branch]
symbol = "ï¡ "
style = "bg:#96ab5f fg:#111111"
format = "[[î‚´](bg:#96ab5f fg:#A6A6A6)$symbol$branch[î‚´](bg:#A6A6A6 fg:#96ab5f)]($style)"

[git_commit]
style = "bg:#E58F73 fg:#111111"
commit_hash_length = 4
format = "[[î‚´](bg:#E58F73 fg:#A6A6A6)#$hash[î‚´](bg:#A6A6A6 fg:#E58F73)]($style)"

[git_state]
style = "bg:#E0B25D fg:111111"
rebase = "rebasing"
merge = "merging"
revert = "reverting"
cherry_pick = "îŠ› picking"
bisect = "bisecting"
am = "am'ing"
am_or_rebase = "am/rebase"
format = '\([[î‚´](bg:#E0B25D fg:#A6A6A6)$state($progress_current/$progress_total)[î‚´](bg:#A6A6A6 fg:#E0B25D)]($style)\)'

[git_status]
style = "red"
behind = "â†“"
ahead = "ï•œ"
diverged = "â†•"

[hostname]
style = "bg:#57686B fg:#111111"
ssh_only = true
trim_at = "."
format = "[[î‚´](bg:#57686B fg:#A6A6A6)($style)$hostname[î‚´](bg:#A6A6A6 fg:#222A36)]($style)"

[jobs]
symbol = ""
style = "bold bg:#A6A6A6 fg:#b4bbc8"
format = "[$symbol$number]($style) "

# Package module. Currently supports npm, cargo, poetry, composer, gradle, julia and mix
[package]
symbol = "ğŸ“¦ "
style = "bold fg:94"
display_private = true
format = "[$symbol$version]($style)"

[python]
symbol = "ğŸ "
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\] '
style = "bg:#EBD45B fg:#111111"
pyenv_prefix = "pyenv "
python_binary = "python3"

[shlvl]
symbol = "ğŸš "
style = "bold bg:#A6A6A6 fg:#d7bd8d"
threshold = 2
format = "[$symbol$shlvl]($style)"

[status]
disabled = false

[time]
disabled = false
use_12hr = false
time_format = "%H:%M"
utc_time_offset = "local"
time_range = "20:00:00-06:00:00"
style = "bold orange"
format = '[\[$time\]]($style) '

[username]
style_root = "bold red"
style_user = "bold yellow"
show_always = false
